services:
  chatbot:
    build:
      context: .
    container_name: ctn_chatbot
    env_file:
      - .env

    ports:
      - 5555:7860

#     volumes:
#       - vector-db:/app/data

# # persist data: it's a paid feature in HF Space, so i comment these lines
# volumes:
#   vector-db: